language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "kH+T8he9cmxOKHdlbdmOcvrdv7+x2mj5o3zXmJRUo7cKUfGvHLwnJp6zf15yIzlQQ7lAX6Yx6RhPeJFFxHeTtW9ncXmdrE7IAWK1npWLVYAtBSdgllIaSGt8WeENsOXVkw4aKBiJ8Xn730qgqx2lAp/OUpSAHipDfzAnAXrtTAj4d0pnPmzx3VUNwa80h5RtmGf2C/NJdkVULwlnGTdcrtjo4cDWnV8Z7yd6xpAsZlhutWSQ0f8H8RWlK4MiViCHBCb72j3vj9yrHe8gFNUo9wDPA9wMVrq7atxGIQGlXKFbQc+XfXeKn8spapUTJa/fc2TpD3qBOxpjGCp1fcNlVVZlyubsh1TQaAPoTwKshDHP+mqi7BIIwEhFp6mfr5WXIOzsVAHpzYD6+e83DcZOe1nXgP8jXDzQnTI69lrcqTZdbgKld1hQ1tozCC9He+kRYWXdbs2QaZOgJnog9A9qYDVpPOGLRxhoIFh/c63u0Ng9JcAACc8f5IaTPrRGaOs41krbBg6eTUqdQmn4Hb1FpyKBEacK6Ubp8YA3p/06QpC7BxVJJYDwd2SWDxcTYT87palCajL2+5gmpSZociBWhc1Jt0YM9xer2FyXDlvjWyIIzG3DvbW0cXTMuhx0i8JpGlBShuWqfqMMrjuRBLC3naJacAoNKxFpG/0uNN/hI1Q="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ensc/hash-x509"
      description: "Build submitted via Travis CI"
    notification_email: github@ensc.de
    build_command_prepend: "true"
    build_command:   "make -j check"
    branch_pattern: master

script:
- make -j check
